### ISSUE TITLE
Heroicon helper have problems when type argument are a symbol.

### ISSUE THREAD

**Issue by 1wilber** [carlweis/heroicon-rails#1]
I don't know if it's a bug, but when I try to use symbols for type (outline, solid) in heroicon helper I get a not found message, but when I use string it works fine.

Example with haml:
```haml
-# this not works
= heroicon 'people', type: :outline

-# this works
= heroicon 'people', type: 'outline'
```

Great work with this gem! regards.

**Comment by bearettoaks** [comment]
@1wilber Thanks for the feedback! I have released a new version that allows for using symbols or strings.
