### ISSUE TITLE
Unclear exception when icon doesn't exist

### ISSUE THREAD

**Issue by clementf** [carlweis/heroicon-rails#2]
Hi @carlweis, first of all, thanks for making this gem!

One thing I noticed, is that if an icon can't be found an unclear exception is raised:

<img width="1013" alt="Screenshot 2024-03-04 at 11 03 48" src="https://github.com/carlweis/heroicon-rails/assets/6423611/5ecc7dee-4277-4398-8aa9-19b74b34c271">

---

I guess that https://github.com/carlweis/heroicon-rails/blob/ef8f138ee4a14f774ee4d09efe6a798e41e3e29a/lib/heroicon/rails/heroicon_helper.rb#L58 could be changed for `rescue StandardError => e`.

**Comment by bearettoaks** [comment]
@clementf Thanks for the feedback. I added your change so the error gets reported.
